[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "/bin/bash /app/docker-entrypoint.sh"
healthcheckPath = "/api/getFaucetConfig"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
